//
//  Constants_ViewIdentifiers.h
//  CrowdBootstrap
//
//  Created by OSX on 26/05/16.
//  Copyright © 2016 trantor.com. All rights reserved.
//

#ifndef Constants_ViewIdentifiers_h
#define Constants_ViewIdentifiers_h


#endif /* Constants_ViewIdentifiers_h */

#pragma mark - View Identifiers
#define kLoginIdentifier                          @"LoginView"
#define kSignUpIdentifier                         @"SignUpView"
#define kForgotPasswordIdentifier                 @"ForgotPasswordView"
#define kHomeIdentifer                            @"HomeView"
#define kGettingStartedIdentifer                  @"GettingStartedView"
#define kMenuIdentifier                           @"MenuView"
#define kCurrentStartupsIdentifier                @"CurrentStartupsView"
#define kProfileIdentifier                        @"ProfileView"
#define kConnectionsIdentifier                    @"connectionsView"
#define kPublicProfileIdentifier                  @"PublicProfileView"
#define kStartupDetailIdentifier                  @"StartupDetailView"
#define kRevealIdentifier                         @"RevealView"
#define kRootNavControllerIdentifier              @"rootNavController"
#define kChooseUserTypeIdentifier                 @"ChooseUserTypeView"
#define kForumsListIdentifier                     @"ForumsListView"
#define kForumDetailIdentifier                    @"ForumDetailView"
#define kAddForumIdentifier                       @"AddForumView"
#define kAddNoteIdentifier                        @"AddNoteView"
#define kAddCampaignIdentifier                    @"AddCampaignView"
#define kAddStartupIdentifier                     @"AddStartupView"
#define kAddContractorIdentifier                  @"AddContractorView"
#define kMessagesIdentifier                       @"messagesView"
#define kInfoIdentifier                           @"InfoView"
#define kSearchStartupIdentifier                  @"SearchStartupView"
#define kCampaignDetailIdentifier                 @"CampaignDetailView"
#define kTeamMessageIdentifier                    @"StartupTeamMessageView"
#define kPopupViewIdentifier                      @"PopupView"
#define kViewContractorIdentifier                 @"ContractorsListView"
#define kCommitViewIdentifier                     @"CommitCampaignView"
#define kAwardViewIdentifier                      @"AwardView"
#define kRateViewIdentifier                       @"RateView"
#define kChatUserViewIdentifier                   @"ChatUserView"
#define kIndependentContractorViewIdentifier      @"IndependentContractorView"
#define kProfileAddStartupViewIdentifier          @"ProfileAddStartupView"
#define kEditCampaignViewIdentifier               @"EditCampaignlView"
#define kStartupOverviewViewIdentifier            @"StartupOverviewView"
#define kSearchContractorViewIdentifier           @"SearchContractorView"
#define kForumCommentsViewIdentifier              @"CommentsView"
#define kNotificationViewIdentifier               @"NotificationView"
#define kOpportunitiesViewIdentifier              @"OpportunitiesView"
#define kShoppingCartDetailViewIdentifier         @"ShoppingCartDetail"
#define kSubmitAppViewIdentifier                  @"SubmitAppView"
#define kStartupProfileViewIdentifier             @"StartupProfileView"
#define kStartupWorkOrderDetailEntIdentifier      @"StartupWorkOrderDetailEntIdentifier"
#define kCompanyDetailIdentifier                  @"CompanyDetailView"
#define kJobDetailIdentifier                      @"JobDetailView"
#define kApplyJobIdentifier                       @"ApplyJobView"
#define kAddExperienceIdentifier                  @"AddExperienceView"
#define kPostJobIdentifier                        @"PostJobView"
#define kEditJobIdentifier                        @"EditJobView"

#pragma mark - Cell Identifers
#define kCellIdentifier_MessagesCell              @"messagesCell"
#define kCellIdentifier_ForumList                 @"forumsCell"
#define TEXTFIELD__CELL_IDENTIFIER                @"TextfieldCell"
#define DESCRIPTION_CELL_IDENTIFIER               @"DescriptionCell"
#define ROADMAP_CELL_IDENTIFIER                   @"RoadmapCell"
#define KEYWORDS_CELL_IDENTIFIER                  @"KeywordsCell"
#define EDIT_ROADMAP_CELL_IDENTIFIER              @"EditRoadmapCell"
#define ROADMAP_GRAPHIC_CELL_IDENTIFIER           @"graphicCell"
#define EDIT_CELL_IDENTIFIER                      @"EditCell"
#define ADD_STARTUP_TITLE                         @"Create Startup"
#define STARTUP_DETAIL_TITLE                      @"Startup Detail"
#define kCellIdentifier_Startups                  @"StartupCell"
#define kCellIdentifier_Notification              @"notificationsCell"
#define AMOUNT_CELL_IDENTIFIER                    @"AmountCell"
#define FOLLOW_CELL_IDENTIFIER                    @"FollowCell"
#define LABEL_CELL_IDENTIFIER                     @"DynamicTableViewCell"
#define KEYWORDS_CELL_IDENTIFIER                  @"KeywordsCell"
#define PLAY_AUDIO_CELL_IDENTIFIER                @"PlayAudioCell"
#define SUMMARY_CELL_IDENTIFIER                   @"SummaryCell"
#define SUBMIT_CELL_IDENTIFIER                    @"SubmitCell"
#define IMAGES_CELL_IDENTIFIER                    @"ImagesCell"
#define kCellIdentifer_LoadMore                   @"LoadMoreCell"
#define kCellIdentifier_Contacts                  @"contactsCell"
#define kCellIdentifier_Chats                     @"ChatListCell"
#define kCellIdentifier_StartupsList              @"currentStartupCell"
#define kCellIdentifier_SuggestKeywords           @"SuggestKeywordsCell"
#define kCellIdentifier_AddExperience             @"AddExperienceCell"
#define kCellIdentifier_Experience                @"ExperienceCell"
