//
//  Constants_ViewIdentifiers.h
//  CrowdBootstrap
//
//  Created by OSX on 26/05/16.
//  Copyright © 2016 trantor.com. All rights reserved.
//

#ifndef Constants_ViewIdentifiers_h
#define Constants_ViewIdentifiers_h


#endif /* Constants_ViewIdentifiers_h */

#pragma mark - View Identifiers
#define kLoginIdentifier                          @"LoginView"
#define kSignUpIdentifier                         @"SignUpView"
#define kForgotPasswordIdentifier                 @"ForgotPasswordView"
#define kHomeIdentifer                            @"HomeView"
#define kGettingStartedIdentifer                  @"GettingStartedView"
#define kVideoViewIdentifier                      @"YTVideoVC"
#define kMenuIdentifier                           @"MenuView"
#define kCurrentStartupsIdentifier                @"CurrentStartupsView"
#define kProfileIdentifier                        @"ProfileView"
#define kConnectionsIdentifier                    @"connectionsView"
#define kPublicProfileIdentifier                  @"PublicProfileView"
#define kStartupDetailIdentifier                  @"StartupDetailView"
#define kWorkOrderContractorIdentifier            @"WorkOrderContractorView"
#define kRevealIdentifier                         @"RevealView"
#define kRootNavControllerIdentifier              @"rootNavController"
#define kChooseUserTypeIdentifier                 @"ChooseUserTypeView"
#define kForumsListIdentifier                     @"ForumsListView"
#define kForumDetailIdentifier                    @"ForumDetailView"
#define kAddForumIdentifier                       @"AddForumView"
#define kAddNoteIdentifier                        @"AddNoteView"
#define kAddCampaignIdentifier                    @"AddCampaignView"
#define kAddStartupIdentifier                     @"AddStartupView"
#define kAddContractorIdentifier                  @"AddContractorView"
#define kMessagesIdentifier                       @"messagesView"
#define kInfoIdentifier                           @"InfoView"
#define kSearchStartupIdentifier                  @"SearchStartupView"
#define kCampaignDetailIdentifier                 @"CampaignDetailView"
#define kTeamMessageIdentifier                    @"StartupTeamMessageView"
#define kPopupViewIdentifier                      @"PopupView"
#define kViewContractorIdentifier                 @"ContractorsListView"
#define kCommitViewIdentifier                     @"CommitCampaignView"
#define kAwardViewIdentifier                      @"AwardView"
#define kRateViewIdentifier                       @"RateView"
#define kChatUserViewIdentifier                   @"ChatUserView"
#define kIndependentContractorViewIdentifier      @"IndependentContractorView"
#define kProfileAddStartupViewIdentifier          @"ProfileAddStartupView"
#define kEditCampaignViewIdentifier               @"EditCampaignlView"
#define kStartupOverviewViewIdentifier            @"StartupOverviewView"
#define kSearchContractorViewIdentifier           @"SearchContractorView"
#define kForumCommentsViewIdentifier              @"CommentsView"
#define kNotificationViewIdentifier               @"NotificationView"
#define kOpportunitiesViewIdentifier              @"OpportunitiesView"
#define kShoppingCartDetailViewIdentifier         @"ShoppingCartDetail"
#define kGroupBuyingViewIdentifier                @"PurchaseOrderView"
#define kLaunchDealsViewIdentifier                @"MyLaunchDealsView"
#define kSubmitAppViewIdentifier                  @"SubmitAppView"
#define kStartupProfileViewIdentifier             @"StartupProfileView"
#define kStartupWorkOrderDetailEntIdentifier      @"StartupWorkOrderDetailEntIdentifier"
#define kCompanyDetailIdentifier                  @"CompanyDetailView"
#define kJobDetailIdentifier                      @"JobDetailView"
#define kApplyJobIdentifier                       @"ApplyJobView"
#define kAddExperienceIdentifier                  @"AddExperienceView"
#define kPostJobIdentifier                        @"PostJobView"
#define kEditJobIdentifier                        @"EditJobView"
#define kCreateFundIdentifier                     @"CreateFundView"
#define kEditFundIdentifier                       @"EditFundView"
#define kCreateBetaTestIdentifier                 @"CreateBetaTestView"
#define kEditBetaTestIdentifier                   @"EditBetaTestView"
#define kCreateBoardMemberIdentifier              @"CreateBoardMemberView"
#define kEditBoardMemberIdentifier                @"EditBoardMemberView"
#define kCreateCommunalAssetIdentifier            @"CreateAssetView"
#define kEditCommunalAssetIdentifier              @"EditAssetView"
#define kCreateConsultingIdentifier               @"CreateConsultingView"
#define kEditConsultingIdentifier                 @"EditConsultingView"
#define kCreateEarlyAdopterIdentifier             @"AddEarlyAdopterView"
#define kEditEarlyAdopterIdentifier               @"EditEarlyAdopterView"
#define kCreateEndorsorIdentifier                 @"CreateEndorsorView"
#define kEditEndorsorIdentifier                   @"EditEndorsorView"
#define kCreateFocusGroupIdentifier               @"CreateFocusGroupView"
#define kEditFocusGroupIdentifier                 @"EditFocusGroupView"
#define kCreateHardwareIdentifier                 @"CreateHardwareView"
#define kEditHardwareIdentifier                   @"EditHardwareView"
#define kCreateSoftwareIdentifier                 @"CreateSoftwareView"
#define kEditSoftwareIdentifier                   @"EditSoftwareView"
#define kCreateServiceIdentifier                  @"CreateServiceView"
#define kEditServiceIdentifier                    @"EditServiceView"
#define kCreateAudioVideoIdentifier               @"CreateAudioVideoView"
#define kEditAudioVideoIdentifier                 @"EditAudioVideoView"
#define kCreateInformationIdentifier              @"CreateInformationView"
#define kEditInformationIdentifier                @"EditInformationView"
#define kCreateProductivityIdentifier             @"CreateProductivityView"
#define kEditProductivityIdentifier               @"EditProductivityView"
#define kCreateGroupIdentifier                    @"CreateGroupView"
#define kEditGroupIdentifier                      @"EditGroupView"
#define kCreateWebinarIdentifier                  @"AddWebinarView"
#define kEditWebinarIdentifier                    @"EditWebinarView"
#define kCreateMeetUpIdentifier                   @"AddMeetUpView"
#define kEditMeetUpIdentifier                     @"EditMeetUpView"
#define kCreateDemoDayIdentifier                  @"AddDemoDayView"
#define kEditDemoDayIdentifier                    @"EditDemoDayView"
#define kCreateDemoDayIdentifier                  @"AddDemoDayView"
#define kEditDemoDayIdentifier                    @"EditDemoDayView"
#define kCreateConferenceIdentifier               @"AddConferenceView"
#define kEditConferenceIdentifier                 @"EditConferenceView"
#define kCreateCareerIdentifier                   @"AddCareerView"
#define kEditCareerIdentifier                     @"EditCareerView"
#define kCreateLaunchDealIdentifier               @"CreateLaunchDealView"
#define kEditLaunchDealIdentifier                 @"EditLaunchDealView"
#define kCreateImprovementToolIdentifier          @"CreateImprovementToolView"
#define kEditImprovementToolIdentifier            @"EditImprovementToolView"
#define kCreatePurchaseOrderIdentifier            @"AddPurchaseOrderView"
#define kEditPurchaseOrderIdentifier              @"EditPurchaseOrderView"
#define kNewsDetailIdentifier                     @"NewsDetailView"
#define kNetworkOptionsIdentifier                 @"NetworkOptionsView"
#define kAddContactIdentifier                     @"AddContactView"
#define kSearchConnectionIdentifier               @"SearchConnectionView"
#define kAddNewUserIdentifier                     @"AddNewUserView"
#define kManageGroupsIdentifier                   @"ManageGroupsView"
#define kManageNotesIdentifier                    @"ManageNotesView"
#define kBusinessCardDetailIdentifier             @"BusinessCardDetailView"
#define kBusinessConnectionListIdentifier         @"ConnectionListView"
#define kAddBusinessCardIdentifier                @"AddBusinessCardView"


#pragma mark - Cell Identifers
#define kCellIdentifier_MessagesCell              @"messagesCell"
#define kCellIdentifier_ForumList                 @"forumsCell"
#define TEXTFIELD__CELL_IDENTIFIER                @"TextfieldCell"
#define DESCRIPTION_CELL_IDENTIFIER               @"DescriptionCell"
#define ROADMAP_CELL_IDENTIFIER                   @"RoadmapCell"
#define KEYWORDS_CELL_IDENTIFIER                  @"KeywordsCell"
#define EDIT_ROADMAP_CELL_IDENTIFIER              @"EditRoadmapCell"
#define ROADMAP_GRAPHIC_CELL_IDENTIFIER           @"graphicCell"
#define EDIT_CELL_IDENTIFIER                      @"EditCell"
#define ADD_STARTUP_TITLE                         @"Create Startup"
#define STARTUP_DETAIL_TITLE                      @"Startup Detail"
#define kCellIdentifier_Startups                  @"StartupCell"
#define kCellIdentifier_Notification              @"notificationsCell"
#define AMOUNT_CELL_IDENTIFIER                    @"AmountCell"
#define FOLLOW_CELL_IDENTIFIER                    @"FollowCell"
#define LABEL_CELL_IDENTIFIER                     @"DynamicTableViewCell"
#define KEYWORDS_CELL_IDENTIFIER                  @"KeywordsCell"
#define PLAY_AUDIO_CELL_IDENTIFIER                @"PlayAudioCell"
#define SUMMARY_CELL_IDENTIFIER                   @"SummaryCell"
#define SUBMIT_CELL_IDENTIFIER                    @"SubmitCell"
#define IMAGES_CELL_IDENTIFIER                    @"ImagesCell"
#define kCellIdentifer_LoadMore                   @"LoadMoreCell"
#define kCellIdentifier_Contacts                  @"contactsCell"
#define kCellIdentifier_Chats                     @"ChatListCell"
#define kCellIdentifier_StartupsList              @"currentStartupCell"
#define kCellIdentifier_SuggestKeywords           @"SuggestKeywordsCell"
#define kCellIdentifier_AddExperience             @"AddExperienceCell"
#define kCellIdentifier_Experience                @"ExperienceCell"
